format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36887ae:
        git: https://github.com/Poorna32/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: dev
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash #bash ansible.sh frontend
                    run_if: passed
      - QA:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: qa
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
      - STAGE:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: stage
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
      - PROD:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: prod
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
